

FROM  amazoncorretto:17.0.12-alpine3.18 as runtime

ARG API_URL
ARG API_LOGIN
ARG API_PASSWORD
ARG API_FILIAL
ARG OMIE_KEY
ARG OMIE_SECRET

ENV APP_NAME wmsexpert
ENV WMS_API_URL=${API_URL}
ENV WMS_API_LOGIN=${API_LOGIN}
ENV WMS_API_PASSWORD=${API_PASSWORD}
ENV WMS_API_FILIAL=${API_FILIAL}
ENV CLIENTE_OMIE_KEY=${OMIE_KEY}
ENV CLIENTE_OMIE_SECRET=${OMIE_SECRET}

ENV APP_NAME wmsexpert-omie
WORKDIR /app

COPY ./target/${APP_NAME}.jar /app/${APP_NAME}.jar

CMD java -jar ${APP_NAME}.jar  --spring.profiles.active=prod

EXPOSE 9597